name: "Auto Update"

on:
  schedule:
    - cron: '45 16 * * *'

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Updated `date`" >> README.md

      - name: Run a multi-line script
        run: |
          git config --global user.email "55233766+lemon-mint@users.noreply.github.com"
          git config --global user.name "lemon-mint"
          git add .
          git commit -m "auto update"
          git push 
